### ISSUE TITLE
2.0.2 only shows 1 image per gallery

### ISSUE THREAD

**Issue by Pentaphon** [anegrin/chiver#11]
No matter what gallery I try to view, it keeps showing me only one image.

2.0.1 seems to work fine, showing all images.

This is on Android 9 with a MotoG7.

**Comment by anegrin** [comment]
Few weeks ago thechive changed their RSS feed so since version 2.x we need to parse the actual html page. It could just be a matter phone slowness

- is it happening all the time or does it properly work sometimes (like when connected to WIFI)?
- how long is your phone taking to load a thechive gallery page like `https://thechive.com/2021/03/15/daily-morning-awesomeness-40-photos-117-2/` ? rough estimation would be enough

we have a hotfix channel for the  script so i can try ti make it work with these info. thanx. 2.0.2 is properly working on my Pixel 2 so we could just make the script more "resilient"

**Comment by Pentaphon** [comment]
2.0.1 works fine for me and takes about 5 seconds to load 72 images into the gallery. My phone has a Snapdragon 632, so it's not a slow phone. Not as fast as a Pixel 2 but fast enough to load an image gallery in a reasonable amount of time. 

2.0.2 only loads 1 image per gallery, all the time. I tried it on 20 different galleries. 

Therefore, it's safe to assume that 2.0.2 introduced a bug that only loads 1 image per gallery, at least for me.

**Comment by anegrin** [comment]
yes i reduced the delay for parsing. i'm pushing a script that should be more resilient on the hotfix branch. let me know if it "starts" working. if so i'm gonna release 2.0.3

**Comment by anegrin** [comment]
if you confirm it's working I can rollout version 2.1.0 - it will also have FR #12

**Comment by Pentaphon** [comment]
Link to test apk?

**Comment by anegrin** [comment]
2.0.2 should automatically download the updated script. please try
relaunching the app.

**Comment by Pentaphon** [comment]
I got 2.0.2 and the updated script works now! Thanks! Closing this. Looking forward to 2.1 with the autoplay feature.
